name: 'Run NATS'
description: 'Runs a NATS server for testing'
inputs:
  options:
    description: 'NATS options, e.g. `-js` for JetStream support'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install NATS
      run: |
        curl -L https://github.com/nats-io/nats-server/releases/download/v2.9.3/nats-server-v2.9.3-linux-amd64.zip -o nats-server.zip
        unzip nats-server.zip -d nats-server
      shell: bash

    - name: Run NATS with options
      run: ./nats-server/nats-server-v2.9.3-linux-amd64/nats-server ${{ inputs.options }} &
      shell: bash

