name: 'Install wash'
description: 'Common action to install the `wash` tool'
inputs:
runs:
  using: "composite"
  steps:
    - name: Install wash
      run: |
        curl -s https://packagecloud.io/install/repositories/wasmCloud/core/script.deb.sh | sudo bash
        sudo apt install wash
      shell: bash
