name: 'Run Redis Server'
description: 'Runs a Redis server for testing'
inputs:
  port:
    description: "Port to expose redis over"
    required: false
    default: 6379
runs:
  using: "composite"
  steps:
    - name: Run Redis via Docker
      run: |
        docker run --name redis -p ${{ inputs.port }}:6379 -d redis
      shell: bash
